version: 2
jobs:
  one:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo
    
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "More"
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
